server:
  port: 8101
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    #url: jdbc:mysql://www.bubbo.top:6002/sp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/sp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #username: sp
    username: root
    #password: sp123
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML

  resources:
    static-locations: classpath:/templates/,classpath:/static/,classpath:/doc/

  devtools:
    restart:
      enabled: true
      exclude: templates,static

# spdate:
#   importErrorPath: /data/sp-sys/import/error
#   importModel: /data/sp-sys/import/importModel.xls
exportPath: /data/sp-sys/export/
logging:
  level: 
    org:
      springframework: WARN
    com.kailash.land.mapper: DEBUG

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.kailash.land.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #数据库大写下划线转换
    capital-mode: true   
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
    
export:
   chartExport: /data/sp_export/project_chart/
   
upload:
  base-dir: /data/sp-upload/
  dirs:
    1: /notice_pic/
    2: /doc_upload/
    3: /demand_upload/
    4: /pic_upload/
    5: /user_upload/
    6: /project_upload/

   
