server:
  port: 8099
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://172.31.48.22:3306/url_sys?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Geewise@123
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  devtools:
    restart:
      enabled: true
      exclude: templates,static
urldate:
  importErrorPath: /data/url-sys/import/error/
  importModel: /data/url-sys/import/importModel.xls
exportPath: /data/url-sys/export/
